name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: true
  push:
    branches:
      - main

jobs:
  Release:
    name: Release the version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js v16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Bump Version & Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
