name: Docs Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Build and Deploy Documentation on GH pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@0066b88440aa9562be742e2c60ee750fc57d8849 # renovate: tag=v2
              with:
                  python-version: 3.x
            - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2
              id: pip-cache
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - if: steps.pip-cache.outputs.cache-hit != 'true'
              run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
            - run: mkdocs gh-deploy --force
