name: Docs Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Build and Deploy Documentation on GH pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # renovate: tag=v2
              with:
                  python-version: 3.x
            - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
            - run: mkdocs gh-deploy --force
